export interface InitialFoodItem {
  name: string;
  category: 'PROTEIN' | 'CARBS' | 'FATS' | 'SUPERFOODS';
  description: string;
  servingSize: number;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  benefits?: string;
  notes?: string;
  orderIndex: number;
}

export const INITIAL_FOODS: InitialFoodItem[] = [
  // ===========================================================================
  // 1. PROTEIN
  // ===========================================================================
  {
    name: 'Chicken',
    category: 'PROTEIN',
    description:
      'Lean skinless chicken breast, the quintessential bodybuilding protein staple.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    notes: 'Weigh raw or cooked consistently. High in niacin and selenium.',
    orderIndex: 1,
  },
  {
    name: 'Salmon',
    category: 'PROTEIN',
    description:
      'Fresh Atlantic or wild salmon fillet rich in high-quality protein and Omega-3s.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    notes: 'Pan sear or bake with lemon and herbs. Loaded with EPA & DHA.',
    orderIndex: 2,
  },
  {
    name: 'Turkey',
    category: 'PROTEIN',
    description:
      'Ultra-lean turkey breast meat with virtually no saturated fats.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1,
    fiber: 0,
    notes: 'Excellent low-calorie cutting phase protein.',
    orderIndex: 3,
  },
  {
    name: 'Beef',
    category: 'PROTEIN',
    description:
      'Lean cuts of beef providing dense complete protein, creatine, and bioavailable iron.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    notes: 'Rich source of zinc, B12, and natural creatine for strength.',
    orderIndex: 4,
  },
  {
    name: 'Tuna',
    category: 'PROTEIN',
    description:
      'Steak or canned in water tuna delivering ultra-pure lean fish protein.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 28,
    carbs: 0,
    fat: 1,
    fiber: 0,
    notes: 'Fast, convenient high-protein snack or meal addition.',
    orderIndex: 5,
  },
  {
    name: 'Ham',
    category: 'PROTEIN',
    description:
      'Cured lean sliced ham protein, versatile for quick breakfasts and wraps.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 145,
    protein: 21,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
    notes: 'Check sodium content when meal planning.',
    orderIndex: 6,
  },
  {
    name: 'Prawns',
    category: 'PROTEIN',
    description:
      'Succulent king or tiger prawns, extremely low in calories with zero carbs.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    notes: 'Quick cooking seafood rich in iodine and astaxanthin.',
    orderIndex: 7,
  },
  {
    name: 'Greek yoghurt',
    category: 'PROTEIN',
    description:
      'Authentic strained 0-2% Greek yogurt rich in slow-digesting casein and whey.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    notes:
      'Contains live active probiotic cultures for optimal gut biome health.',
    orderIndex: 8,
  },
  {
    name: 'Eggs',
    category: 'PROTEIN',
    description:
      'Whole large eggs providing the gold standard biological value protein.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 143,
    protein: 13,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0,
    notes: 'Each large egg is approx 50g (72 kcal, 6.5g protein).',
    orderIndex: 9,
  },
  {
    name: 'Lentils',
    category: 'PROTEIN',
    description:
      'Cooked green/brown lentils, dense in plant-based amino acids and prebiotic fiber.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    notes: 'Hearty vegan and vegetarian staple with sustained glucose release.',
    orderIndex: 10,
  },
  {
    name: 'Tofu',
    category: 'PROTEIN',
    description:
      'Firm organic soybean curd, adaptable protein with isoflavones and calcium.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    fiber: 0.3,
    notes: 'Press before cooking to absorb marinades and spices.',
    orderIndex: 11,
  },
  {
    name: 'Seitan',
    category: 'PROTEIN',
    description:
      'Vital wheat gluten plant protein with meat-like texture and huge protein density.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 370,
    protein: 75,
    carbs: 14,
    fat: 1.9,
    fiber: 1.5,
    notes: 'Highest concentration plant-based protein available.',
    orderIndex: 12,
  },
  {
    name: 'Vegan protein',
    category: 'PROTEIN',
    description:
      'Multi-source plant protein blend (pea, rice, pumpkin, hemp) powder.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 380,
    protein: 75,
    carbs: 5,
    fat: 5,
    fiber: 4,
    notes: '1 scoop typically ~30g providing ~24g protein.',
    orderIndex: 13,
  },

  // ===========================================================================
  // 2. CARBS
  // ===========================================================================
  {
    name: 'Rice',
    category: 'CARBS',
    description:
      'Steamed jasmine, basmati, or brown rice for fast glycogen replenishment.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    notes: 'Easy on the digestive system, ideal pre- and post-workout fuel.',
    orderIndex: 14,
  },
  {
    name: 'Quinoa',
    category: 'CARBS',
    description:
      'Nutty ancient grain containing all nine essential amino acids and complex carbs.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    notes: 'Cook in 2:1 water ratio for light, fluffy grain consistency.',
    orderIndex: 15,
  },
  {
    name: 'Couscous',
    category: 'CARBS',
    description:
      'Steamed durum wheat semolina pearls, quick to prepare with light digestion.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 112,
    protein: 3.8,
    carbs: 23,
    fat: 0.2,
    fiber: 1.4,
    notes: 'Pairs excellently with roasted vegetables and lean meats.',
    orderIndex: 16,
  },
  {
    name: 'Rice cakes',
    category: 'CARBS',
    description:
      'Puffed whole grain rice cakes for clean, instant carbohydrate energy.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 387,
    protein: 8,
    carbs: 82,
    fat: 2.8,
    fiber: 4,
    notes: '1 standard rice cake is ~9-10g (~35 kcal, 7.5g carbs).',
    orderIndex: 17,
  },
  {
    name: 'Oats',
    category: 'CARBS',
    description:
      'Rolled whole oats rich in beta-glucan soluble fiber for sustained all-morning energy.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    notes: 'Low glycemic index carb that stabilizes blood glucose levels.',
    orderIndex: 18,
  },
  {
    name: 'Granola',
    category: 'CARBS',
    description:
      'Toasted oat clusters with seeds and natural sweetness for energy-dense meals.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 471,
    protein: 10,
    carbs: 64,
    fat: 20,
    fiber: 5,
    notes: 'Great topping for Greek yogurt and smoothie bowls.',
    orderIndex: 19,
  },
  {
    name: 'Sweet Potato',
    category: 'CARBS',
    description:
      'Baked or steamed sweet potato rich in beta-carotene (Vitamin A) and complex starch.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3,
    notes: 'High potassium electrolyte content prevents muscle cramps.',
    orderIndex: 20,
  },
  {
    name: 'Potato',
    category: 'CARBS',
    description:
      'Boiled or baked whole white/russet potatoes, top ranking on the satiety index.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 77,
    protein: 2,
    carbs: 17.5,
    fat: 0.1,
    fiber: 2.2,
    notes: 'Extremely filling source of clean carbohydrate and vitamin C.',
    orderIndex: 21,
  },
  {
    name: 'Bagels',
    category: 'CARBS',
    description:
      'Dense, chewy baked wheat bagels ideal for high-carb refeeds and pre-workout pumps.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 10,
    carbs: 48,
    fat: 1.5,
    fiber: 2.3,
    notes: '1 medium bagel is approx 90-100g (~250 kcal, 48g carbs).',
    orderIndex: 22,
  },
  {
    name: 'Pasta',
    category: 'CARBS',
    description:
      'Durum semolina pasta for reliable, steady-burning athletic fuel.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    notes:
      'Values reflect cooked pasta. Cook al dente for lowest glycemic index.',
    orderIndex: 23,
  },

  // ===========================================================================
  // 3. FATS
  // ===========================================================================
  {
    name: 'Avocado',
    category: 'FATS',
    description:
      'Fresh Haas avocado rich in heart-healthy monounsaturated oleic acid and potassium.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    notes:
      'Boosts absorption of fat-soluble vitamins A, D, E, K from other foods.',
    orderIndex: 24,
  },
  {
    name: 'Olive oil',
    category: 'FATS',
    description:
      'Cold-pressed extra virgin olive oil packed with polyphenols and oleocanthal.',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    notes: '1 tablespoon (~14ml) is approx 120 kcal and 14g healthy fats.',
    orderIndex: 25,
  },
  {
    name: 'Butter',
    category: 'FATS',
    description:
      'Grass-fed dairy butter rich in butyrate, conjugated linoleic acid (CLA), and vitamin K2.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 717,
    protein: 0.9,
    carbs: 0.1,
    fat: 81,
    fiber: 0,
    notes: '1 teaspoon (~5g) is approx 36 kcal.',
    orderIndex: 26,
  },
  {
    name: 'Coconut oil',
    category: 'FATS',
    description:
      'Pure virgin coconut oil rich in medium chain triglycerides (lauric & caprylic acid).',
    servingSize: 100,
    servingUnit: 'g',
    calories: 862,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    notes: 'MCTs are readily converted by the liver into usable ketone energy.',
    orderIndex: 27,
  },
  {
    name: 'Peanut butter',
    category: 'FATS',
    description:
      '100% roasted peanut butter delivering rich monounsaturated fats and plant protein.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    notes: '1 tablespoon (~16g) is approx 94 kcal and 8g fats.',
    orderIndex: 28,
  },
  {
    name: 'Cashews',
    category: 'FATS',
    description:
      'Whole roasted or raw cashew nuts rich in magnesium, copper, and monounsaturated lipids.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 553,
    protein: 18,
    carbs: 30,
    fat: 44,
    fiber: 3.3,
    notes: 'Promotes muscle relaxation and bone mineral density.',
    orderIndex: 29,
  },
  {
    name: 'Dark chocolate',
    category: 'FATS',
    description:
      '85%+ premium cacao dark chocolate loaded with epicatechins and flavonoids.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 598,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    fiber: 10.9,
    notes:
      'Improves blood flow, nitric oxide production, and cognitive alertness.',
    orderIndex: 30,
  },
  {
    name: 'Dairy',
    category: 'FATS',
    description:
      'Full-fat dairy, cheese, and whole milk containing bioavailable calcium and phospholipids.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    notes: 'Supports hormone synthesis and bone structural integrity.',
    orderIndex: 31,
  },

  // ===========================================================================
  // 4. SUPERFOODS
  // ===========================================================================
  {
    name: 'Steak',
    category: 'SUPERFOODS',
    description:
      'Grass-fed ribeye or sirloin steak offering supreme bioavailable micro-nutrition.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 271,
    protein: 26,
    carbs: 0,
    fat: 18,
    fiber: 0,
    benefits:
      'High concentration of L-carnitine, creatine, heme iron, and testosterone-supporting zinc.',
    notes: 'Cook medium-rare to preserve micronutrient profiles.',
    orderIndex: 32,
  },
  {
    name: 'Beef liver',
    category: 'SUPERFOODS',
    description:
      "Nature's ultimate multivitamin, surpassing almost all plant & animal foods in nutrient density.",
    servingSize: 100,
    servingUnit: 'g',
    calories: 135,
    protein: 20.4,
    carbs: 3.9,
    fat: 3.6,
    fiber: 0,
    benefits:
      'Extraordinary levels of preformed Vitamin A (retinol), Vitamin B12, copper, folate, and CoQ10.',
    notes:
      'Consume 100-150g once or twice weekly for unparalleled energy and stamina.',
    orderIndex: 33,
  },
  {
    name: 'Whole eggs',
    category: 'SUPERFOODS',
    description:
      'Pasture-raised complete eggs containing the yolk and all fat-soluble micronutrients.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 143,
    protein: 13,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0,
    benefits:
      'Loaded with choline for cognitive neural firing, lutein, and zeaxanthin for vision.',
    notes:
      'Keep the yolks runny to preserve delicate antioxidants and phospholipids.',
    orderIndex: 34,
  },
  {
    name: 'Banana',
    category: 'SUPERFOODS',
    description:
      'Fresh ripe bananas providing instant electrolytic potassium and vitamin B6.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    benefits:
      'Rapid glycogen delivery and nervous system support during strenuous training.',
    notes: '1 medium banana is approx 100-120g.',
    orderIndex: 35,
  },
  {
    name: 'Apple',
    category: 'SUPERFOODS',
    description:
      'Crisp whole apples rich in quercetin polyphenols and pectin soluble fiber.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    benefits:
      'Quercetin acts as a natural antihistamine and cellular longevity antioxidant.',
    notes: 'Eat with the skin on for maximum flavonoid and fiber absorption.',
    orderIndex: 36,
  },
  {
    name: 'Grapes',
    category: 'SUPERFOODS',
    description:
      'Dark red and black grapes packed with resveratrol and cellular hydration electrolytes.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    protein: 0.7,
    carbs: 18.1,
    fat: 0.2,
    fiber: 0.9,
    benefits:
      'Resveratrol activates SIRT1 longevity enzymes and enhances endothelial nitric oxide.',
    notes: 'Great quick workout carb snack.',
    orderIndex: 37,
  },
  {
    name: 'Broccoli',
    category: 'SUPERFOODS',
    description:
      'Cruciferous florets containing potent sulforaphane and estrogen-modulating compounds.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    benefits:
      'Sulforaphane boosts Nrf2 antioxidant pathway; Diindolylmethane (DIM) optimizes hormone balance.',
    notes:
      'Lightly steam for 3-4 minutes to maximize sulforaphane bioavailability.',
    orderIndex: 38,
  },
  {
    name: 'Mushrooms',
    category: 'SUPERFOODS',
    description:
      'Culinary and medicinal mushrooms packed with beta-glucans and ergothioneine.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 22,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1,
    benefits:
      'Ergothioneine is the master intracellular antioxidant that shields mitochondrial DNA.',
    notes: 'Sauté in butter or olive oil with garlic.',
    orderIndex: 39,
  },
  {
    name: 'Spinach',
    category: 'SUPERFOODS',
    description:
      'Tender baby spinach leaves loaded with dietary nitrates, magnesium, and folate.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    benefits:
      'Natural nitrates convert to nitric oxide, boosting vasodilation, pump, and oxygen delivery.',
    notes:
      'Add raw into morning smoothies or gently wilt into eggs and chicken.',
    orderIndex: 40,
  },
  {
    name: 'Onions',
    category: 'SUPERFOODS',
    description:
      'Pungent allium bulbs packed with quercetin, allicin, and prebiotic fructooligosaccharides.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    benefits:
      'Suppresses inflammatory pathways, supports healthy testosterone synthesis and gut microbiota.',
    notes:
      'Red and yellow onions contain the highest concentration of flavonoids.',
    orderIndex: 41,
  },
  {
    name: 'Beets',
    category: 'SUPERFOODS',
    description:
      'Whole ruby red beets packed with concentrated inorganic nitrates and betalains.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 43,
    protein: 1.6,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    benefits:
      'Clinically proven to boost time-to-exhaustion, muscle oxygen efficiency, and athletic endurance.',
    notes: 'Roast whole or juice 2 hours before demanding workouts.',
    orderIndex: 42,
  },
  {
    name: 'Irish sea-moss',
    category: 'SUPERFOODS',
    description:
      'Chondrus crispus wildcrafted marine algae boasting 92 essential trace minerals.',
    servingSize: 100,
    servingUnit: 'g',
    calories: 49,
    protein: 1.5,
    carbs: 12.3,
    fat: 0.2,
    fiber: 1.3,
    benefits:
      'Provides natural organic iodine, potassium iodide, selenium, and sulfur for thyroid & joint health.',
    notes: 'Take 1-2 tablespoons (15-30g) of sea moss gel daily.',
    orderIndex: 43,
  },
];
